// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Tiflo.Info

static UINT QtVirtualKey(QKeyEvent *event){
    UINT key=static_cast<UINT>(event->nativeVirtualKey());if(key)return key;int qtKey=event->key();
    if(qtKey>=Qt::Key_A&&qtKey<=Qt::Key_Z)return static_cast<UINT>('A'+qtKey-Qt::Key_A);
    if(qtKey>=Qt::Key_0&&qtKey<=Qt::Key_9)return static_cast<UINT>('0'+qtKey-Qt::Key_0);
    if(qtKey>=Qt::Key_F1&&qtKey<=Qt::Key_F24)return static_cast<UINT>(VK_F1+qtKey-Qt::Key_F1);
    switch(qtKey){case Qt::Key_Space:return VK_SPACE;case Qt::Key_Backspace:return VK_BACK;case Qt::Key_Delete:return VK_DELETE;case Qt::Key_Insert:return VK_INSERT;case Qt::Key_Home:return VK_HOME;case Qt::Key_End:return VK_END;case Qt::Key_PageUp:return VK_PRIOR;case Qt::Key_PageDown:return VK_NEXT;case Qt::Key_Left:return VK_LEFT;case Qt::Key_Right:return VK_RIGHT;case Qt::Key_Up:return VK_UP;case Qt::Key_Down:return VK_DOWN;case Qt::Key_Pause:return VK_PAUSE;case Qt::Key_Print:return VK_SNAPSHOT;default:return 0;}
}

class QtShortcutCaptureEdit final:public QLineEdit{
public:
    std::function<void(key_combo)> captured;
    std::function<void(const QString&)> rejected;
    std::function<void()> acceptRequested;
    explicit QtShortcutCaptureEdit(QWidget *parent=nullptr):QLineEdit(parent){setReadOnly(true);setAccessibleName(LText(LocalText::Shortcut));setAccessibleDescription(LText(LocalText::ShortcutInstructions));}
protected:
    void keyPressEvent(QKeyEvent *event) override{
        if(event->key()==Qt::Key_Return||event->key()==Qt::Key_Enter){if(acceptRequested)acceptRequested();event->accept();return;}if(event->key()==Qt::Key_Tab||event->key()==Qt::Key_Backtab||event->key()==Qt::Key_Escape){QLineEdit::keyPressEvent(event);return;}
        UINT key=QtVirtualKey(event);Qt::KeyboardModifiers modifiers=event->modifiers();bool ctrl=modifiers.testFlag(Qt::ControlModifier),alt=modifiers.testFlag(Qt::AltModifier),shift=modifiers.testFlag(Qt::ShiftModifier),win=modifiers.testFlag(Qt::MetaModifier);if(!key){if(rejected)rejected(LText(LocalText::KeyCannotAssign));QApplication::beep();event->accept();return;}if(ReservedShortcut(key,ctrl,alt,shift,win)){if(rejected)rejected(LText(LocalText::ReservedShortcut));QApplication::beep();event->accept();return;}int obsKey=ObsKeyFromVirtualKey(key);if(obsKey<=0){if(rejected)rejected(LText(LocalText::ObsUnknownKey));QApplication::beep();event->accept();return;}key_combo combo{(ctrl?OBS_MOD_CONTROL:0u)|(alt?OBS_MOD_ALT:0u)|(shift?OBS_MOD_SHIFT:0u),obsKey};if(captured)captured(combo);event->accept();
    }
};

class QtHotkeyAssignmentDialog final:public QDialog{
    size_t index{};std::vector<key_combo> bindings,originalBindings;QListWidget *assignments{};QtShortcutCaptureEdit *capture{};QPushButton *removeButton{};QLabel *status{};bool append{},armed{true};
    void setStatus(const QString &message){if(status->text()!=message)status->setText(message);}
    void announce(const QString &message){setStatus(message);QAccessibleAnnouncementEvent event(this,message);event.setPoliteness(QAccessible::AnnouncementPoliteness::Assertive);QAccessible::updateAccessibility(&event);}
    void updateControls(){removeButton->setEnabled(assignments->currentRow()>=0&&!bindings.empty());}
    void refresh(){int selected=assignments->currentRow();QSignalBlocker blocker(assignments);assignments->clear();for(key_combo combo:bindings)assignments->addItem(QString::fromStdWString(ComboText(combo)));if(!bindings.empty()){selected=std::clamp(selected,0,static_cast<int>(bindings.size())-1);assignments->setCurrentRow(selected);if(!append)capture->setText(QString::fromStdWString(ComboText(bindings[static_cast<size_t>(selected)])));}else capture->setText(LText(LocalText::None));updateControls();}
    void receive(key_combo combo){if(!armed){announce(LText(LocalText::ChooseAssignmentFirst));QApplication::beep();return;}if(std::any_of(bindings.begin(),bindings.end(),[&](key_combo existing){return CombosEqual(existing,combo); })){announce(LText(LocalText::DuplicateAssignment));QApplication::beep();return;}int selected=assignments->currentRow();QString text=QString::fromStdWString(ComboText(combo));if(append||selected<0){bindings.push_back(combo);assignments->addItem(text);assignments->setCurrentRow(assignments->count()-1);}else{bindings[static_cast<size_t>(selected)]=combo;assignments->item(selected)->setText(text);}append=false;armed=false;capture->setText(text);setStatus(LText(LocalText::ShortcutCaptured).arg(text));updateControls();}
    void tryAccept(){
        struct Conflict{key_combo combo;size_t otherIndex;};std::vector<Conflict> conflicts;auto distinct=DistinctCommandIndices();
        for(key_combo combo:bindings){bool newlyAssigned=std::none_of(originalBindings.begin(),originalBindings.end(),[&](key_combo original){return CombosEqual(original,combo);});if(!newlyAssigned)continue;for(size_t otherIndex=0;otherIndex<hotkeys.size();++otherIndex){if(otherIndex==index||SameLogicalCommand(hotkeys[index],hotkeys[otherIndex]))continue;bool assigned=std::any_of(hotkeys[otherIndex].bindings.begin(),hotkeys[otherIndex].bindings.end(),[&](key_combo candidate){return CombosEqual(candidate,combo);});if(!assigned)continue;bool alreadyListed=std::any_of(conflicts.begin(),conflicts.end(),[&](const Conflict &existing){return CombosEqual(existing.combo,combo)&&SameLogicalCommand(hotkeys[existing.otherIndex],hotkeys[otherIndex]);});if(!alreadyListed)conflicts.push_back({combo,otherIndex});}}
        for(const Conflict &conflict:conflicts){QString shortcut=QString::fromStdWString(ComboText(conflict.combo)),command=QString::fromStdWString(CommandDisplayLabel(conflict.otherIndex,distinct));QMessageBox box(QMessageBox::Warning,QString::fromWCharArray(Tr(UiText::ConflictTitle)),LText(LocalText::ReassignConflictMessage).arg(shortcut,command),QMessageBox::NoButton,this);QPushButton *yes=box.addButton(LText(LocalText::Yes),QMessageBox::AcceptRole);QPushButton *no=box.addButton(LText(LocalText::No),QMessageBox::RejectRole);box.setDefaultButton(no);box.setEscapeButton(no);box.exec();if(box.clickedButton()!=yes){capture->setFocus(Qt::OtherFocusReason);return;}}
        for(key_combo combo:bindings){bool newlyAssigned=std::none_of(originalBindings.begin(),originalBindings.end(),[&](key_combo original){return CombosEqual(original,combo);});if(!newlyAssigned)continue;for(size_t otherIndex=0;otherIndex<hotkeys.size();++otherIndex){if(otherIndex==index||SameLogicalCommand(hotkeys[index],hotkeys[otherIndex]))continue;auto &otherBindings=hotkeys[otherIndex].bindings;otherBindings.erase(std::remove_if(otherBindings.begin(),otherBindings.end(),[&](key_combo candidate){return CombosEqual(candidate,combo);}),otherBindings.end());}}
        hotkeys[index].bindings=bindings;accept();
    }
public:
    QtHotkeyAssignmentDialog(size_t hotkeyIndex,QWidget *parent):QDialog(parent),index(hotkeyIndex),bindings(hotkeys[hotkeyIndex].bindings),originalBindings(bindings){
        setWindowTitle(LText(LocalText::HotKey));setWindowModality(Qt::WindowModal);auto *layout=new QVBoxLayout(this);auto distinct=DistinctCommandIndices();QString commandText=QString::fromStdWString(CommandDisplayLabel(index,distinct));auto *command=new QLabel(LText(LocalText::CommandFormat).arg(commandText),this);command->setWordWrap(true);command->setAccessibleName(QStringLiteral(" "));command->setAccessibleDescription(QStringLiteral(" "));layout->addWidget(command);auto *assignedLabel=new QLabel(QStringLiteral("&")+LText(LocalText::AssignedShortcuts)+QStringLiteral(":"),this);assignments=new QListWidget(this);assignments->setAccessibleName(LText(LocalText::AssignedShortcuts));assignments->setAccessibleDescription(LText(LocalText::AssignmentListHelp));assignments->setTabKeyNavigation(false);assignedLabel->setBuddy(assignments);layout->addWidget(assignedLabel);layout->addWidget(assignments);
        auto *captureLabel=new QLabel(LText(LocalText::ShortcutLabel),this);capture=new QtShortcutCaptureEdit(this);capture->setAccessibleDescription(LText(LocalText::CommandCaptureHelp).arg(commandText));captureLabel->setBuddy(capture);layout->addWidget(captureLabel);layout->addWidget(capture);status=new QLabel(this);status->setWordWrap(true);status->setAccessibleName(QStringLiteral(" "));status->setAccessibleDescription(QStringLiteral(" "));layout->addWidget(status);auto *bindingButtons=new QHBoxLayout;auto *addAnother=new QPushButton(LText(LocalText::AddAnotherShortcut),this);removeButton=new QPushButton(LText(LocalText::RemoveShortcut),this);bindingButtons->addWidget(addAnother);bindingButtons->addWidget(removeButton);bindingButtons->addStretch();layout->addLayout(bindingButtons);auto *buttons=new QDialogButtonBox(QDialogButtonBox::Ok|QDialogButtonBox::Cancel,this);layout->addWidget(buttons);QPushButton *ok=buttons->button(QDialogButtonBox::Ok),*cancel=buttons->button(QDialogButtonBox::Cancel);ok->setText(LText(LocalText::Ok));cancel->setText(LText(LocalText::Cancel));QWidget::setTabOrder(assignments,capture);QWidget::setTabOrder(capture,addAnother);QWidget::setTabOrder(addAnother,removeButton);QWidget::setTabOrder(removeButton,ok);QWidget::setTabOrder(ok,cancel);
        capture->captured=[this](key_combo combo){receive(combo);};capture->rejected=[this](const QString &message){announce(message);};capture->acceptRequested=[this]{tryAccept();};QObject::connect(assignments,&QListWidget::currentRowChanged,[this](int row){if(row>=0&&row<static_cast<int>(bindings.size())){append=false;armed=true;capture->setText(QString::fromStdWString(ComboText(bindings[static_cast<size_t>(row)])));}updateControls();});QObject::connect(addAnother,&QPushButton::clicked,[this]{append=true;armed=true;capture->setText(LText(LocalText::None));setStatus(QString());capture->setFocus(Qt::OtherFocusReason);});QObject::connect(removeButton,&QPushButton::clicked,[this]{int selected=assignments->currentRow();if(selected<0||selected>=static_cast<int>(bindings.size())){announce(LText(LocalText::SelectShortcutToRemove));QApplication::beep();return;}QString removed=assignments->item(selected)->text();bindings.erase(bindings.begin()+selected);delete assignments->takeItem(selected);append=bindings.empty();armed=true;if(!bindings.empty()){int next=std::min(selected,static_cast<int>(bindings.size())-1);assignments->setCurrentRow(next);assignments->setFocus(Qt::OtherFocusReason);setStatus(LText(LocalText::RemovedShortcut).arg(removed));}else{capture->setText(LText(LocalText::None));capture->setFocus(Qt::OtherFocusReason);announce(LText(LocalText::RemovedShortcut).arg(removed));}updateControls();});QObject::connect(buttons,&QDialogButtonBox::accepted,[this]{tryAccept();});QObject::connect(buttons,&QDialogButtonBox::rejected,this,&QDialog::reject);refresh();resize(600,450);capture->setFocus(Qt::OtherFocusReason);
    }
};

static constexpr int COMMAND_TEXT_ROLE=Qt::UserRole+1,SHORTCUT_TEXT_ROLE=Qt::UserRole+2;

class QtHotkeyListDelegate final:public QStyledItemDelegate{
public:
    using QStyledItemDelegate::QStyledItemDelegate;
    void paint(QPainter *painter,const QStyleOptionViewItem &option,const QModelIndex &index) const override{
        QStyleOptionViewItem background(option);initStyleOption(&background,index);background.text.clear();QStyledItemDelegate::paint(painter,background,index);QRect content=option.rect.adjusted(8,0,-8,0);int shortcutWidth=std::clamp(content.width()/3,180,360);QRect commandRect=content;commandRect.setRight(content.right()-shortcutWidth-12);QRect shortcutRect=content;shortcutRect.setLeft(commandRect.right()+13);QColor color=(option.state&QStyle::State_Selected)?option.palette.color(QPalette::HighlightedText):option.palette.color(QPalette::Text);painter->save();painter->setPen(color);QString command=option.fontMetrics.elidedText(index.data(COMMAND_TEXT_ROLE).toString(),Qt::ElideRight,commandRect.width());QString shortcut=option.fontMetrics.elidedText(index.data(SHORTCUT_TEXT_ROLE).toString(),Qt::ElideLeft,shortcutRect.width());painter->drawText(commandRect,Qt::AlignVCenter|Qt::AlignLeft,command);painter->drawText(shortcutRect,Qt::AlignVCenter|Qt::AlignRight,shortcut);painter->restore();
    }
};

class QtCommandList final:public QListWidget{
public:
    std::function<void()> editRequested,removeRequested,closeRequested;
    using QListWidget::QListWidget;
protected:
    void keyPressEvent(QKeyEvent *event) override{if(event->key()==Qt::Key_Return||event->key()==Qt::Key_Enter){if(editRequested)editRequested();event->accept();return;}if(event->key()==Qt::Key_Delete){if(removeRequested)removeRequested();event->accept();return;}if(event->key()==Qt::Key_Escape){if(closeRequested)closeRequested();event->accept();return;}QListWidget::keyPressEvent(event);}
};

class QtHotkeyEditorDialog final:public QDialog{
    QLineEdit *search{};QtCommandList *commands{};QCheckBox *allowObsHotkeyControl{};QPushButton *editButton{},*removeButton{};QLabel *status{};bool closing{},originalAllowObsHotkeyControl{};
    int selectedIndex() const{QListWidgetItem *item=commands->currentItem();return item?item->data(Qt::UserRole).toInt():-1;}
    void setStatus(const QString &message){if(status->text()!=message)status->setText(message);}
    void announce(const QString &message){setStatus(message);QAccessibleAnnouncementEvent event(this,message);event.setPoliteness(QAccessible::AnnouncementPoliteness::Assertive);QAccessible::updateAccessibility(&event);}
    void updateButtons(){int selected=selectedIndex();editButton->setEnabled(selected>=0);removeButton->setEnabled(selected>=0&&!hotkeys[static_cast<size_t>(selected)].bindings.empty());}
    void refresh(int preferred=-1){QString needle=search->text();auto distinct=DistinctCommandIndices();QSignalBlocker blocker(commands);commands->clear();QListWidgetItem *preferredItem=nullptr;for(size_t i:distinct){QString command=QString::fromStdWString(CommandDisplayLabel(i,distinct));QString context=QString::fromUtf8(hotkeys[i].context.c_str());if(!needle.isEmpty()&&!command.contains(needle,Qt::CaseInsensitive)&&!context.contains(needle,Qt::CaseInsensitive))continue;QString shortcut=QString::fromStdWString(BindingSummary(hotkeys[i]));auto *item=new QListWidgetItem(LText(LocalText::CommandListItem).arg(command,shortcut),commands);item->setData(Qt::UserRole,static_cast<int>(i));item->setData(COMMAND_TEXT_ROLE,command);item->setData(SHORTCUT_TEXT_ROLE,shortcut);if(static_cast<int>(i)==preferred)preferredItem=item;}if(preferredItem)commands->setCurrentItem(preferredItem);else if(commands->count()>0)commands->setCurrentRow(0);updateButtons();setStatus(LText(LocalText::CommandsShown).arg(commands->count()));}
    void updateVisibleItems(){for(int row=0;row<commands->count();++row){QListWidgetItem *item=commands->item(row);int hotkeyIndex=item->data(Qt::UserRole).toInt();QString command=item->data(COMMAND_TEXT_ROLE).toString(),shortcut=QString::fromStdWString(BindingSummary(hotkeys[static_cast<size_t>(hotkeyIndex)]));item->setText(LText(LocalText::CommandListItem).arg(command,shortcut));item->setData(SHORTCUT_TEXT_ROLE,shortcut);}commands->viewport()->update();updateButtons();}
    void updateCurrentItem(){QListWidgetItem *item=commands->currentItem();int selected=selectedIndex();if(!item||selected<0)return;QString command=item->data(COMMAND_TEXT_ROLE).toString(),shortcut=QString::fromStdWString(BindingSummary(hotkeys[static_cast<size_t>(selected)]));item->setText(LText(LocalText::CommandListItem).arg(command,shortcut));item->setData(SHORTCUT_TEXT_ROLE,shortcut);commands->viewport()->update();updateButtons();}
    void editSelected(){int selected=selectedIndex();if(selected<0){QApplication::beep();return;}QtHotkeyAssignmentDialog dialog(static_cast<size_t>(selected),this);if(dialog.exec()==QDialog::Accepted)updateVisibleItems();}
    void removeSelected(){int selected=selectedIndex();if(selected<0){QApplication::beep();return;}if(hotkeys[static_cast<size_t>(selected)].bindings.empty()){announce(LText(LocalText::NoShortcutsToRemove));QApplication::beep();return;}QString command=commands->currentItem()->data(COMMAND_TEXT_ROLE).toString();hotkeys[static_cast<size_t>(selected)].bindings.clear();updateCurrentItem();setStatus(LText(LocalText::RemovedAllShortcuts).arg(command));}
    bool dirty() const{return EditorDirty()||allowObsHotkeyControl->isChecked()!=originalAllowObsHotkeyControl;}
    bool saveAll(){if(SaveEditorChanges(this)!=EditorSaveResult::Saved)return false;bool allow=allowObsHotkeyControl->isChecked();if(allow!=originalAllowObsHotkeyControl&&!SaveObsHotkeyManagementPreference(allow)){QMessageBox::critical(this,QStringLiteral("Accessible OBS Studio"),LText(LocalText::HotkeyPolicySaveFailure));return false;}originalAllowObsHotkeyControl=allow;return true;}
    void discard(){for(Hotkey &hotkey:hotkeys)hotkey.bindings=hotkey.originalBindings;allowObsHotkeyControl->setChecked(originalAllowObsHotkeyControl);}
protected:
    void closeEvent(QCloseEvent *event) override{
        if(closing||!dirty()){event->accept();return;}QMessageBox box(QMessageBox::Question,QStringLiteral("Accessible OBS Studio"),LText(LocalText::UnsavedChanges),QMessageBox::Save|QMessageBox::Discard|QMessageBox::Cancel,this);box.setInformativeText(LText(LocalText::UnsavedDetail));box.button(QMessageBox::Save)->setText(LText(LocalText::Save));box.button(QMessageBox::Discard)->setText(LText(LocalText::Discard));box.button(QMessageBox::Cancel)->setText(LText(LocalText::Cancel));box.setDefaultButton(QMessageBox::Save);int choice=box.exec();if(choice==QMessageBox::Save){if(saveAll()){closing=true;event->accept();}else event->ignore();}else if(choice==QMessageBox::Discard){discard();closing=true;event->accept();}else event->ignore();
    }
    void reject() override{close();}
public:
    explicit QtHotkeyEditorDialog(QWidget *parent):QDialog(parent){
        setWindowTitle(QStringLiteral("Accessible OBS Studio — ")+LText(LocalText::ShortcutEditor));setAttribute(Qt::WA_DeleteOnClose);
        auto *layout=new QVBoxLayout(this);auto *searchLabel=new QLabel(LText(LocalText::FindCommands),this);search=new QLineEdit(this);search->setAccessibleName(LText(LocalText::FindCommands));searchLabel->setBuddy(search);layout->addWidget(searchLabel);layout->addWidget(search);
        auto *headers=new QHBoxLayout;auto *commandHeader=new QLabel(LText(LocalText::Command),this);auto *shortcutHeader=new QLabel(LText(LocalText::AssignedShortcuts),this);shortcutHeader->setAlignment(Qt::AlignRight);headers->addWidget(commandHeader,2);headers->addWidget(shortcutHeader,1);layout->addLayout(headers);
        commands=new QtCommandList(this);commands->setItemDelegate(new QtHotkeyListDelegate(commands));commands->setAccessibleName(LText(LocalText::Commands));commands->setAccessibleDescription(LText(LocalText::CommandListHelp));commands->setSelectionMode(QAbstractItemView::SingleSelection);commands->setEditTriggers(QAbstractItemView::NoEditTriggers);commands->setTabKeyNavigation(false);layout->addWidget(commands);
        status=new QLabel(this);status->setWordWrap(true);status->setAccessibleName(QStringLiteral(" "));status->setAccessibleDescription(QStringLiteral(" "));layout->addWidget(status);allowObsHotkeyControl=new QCheckBox(LText(LocalText::AllowObsManageHotkeys),this);originalAllowObsHotkeyControl=AllowObsToManageHotkeysOutsideObs();allowObsHotkeyControl->setChecked(originalAllowObsHotkeyControl);layout->addWidget(allowObsHotkeyControl);auto *buttons=new QDialogButtonBox(this);editButton=buttons->addButton(LText(LocalText::AddOrEdit),QDialogButtonBox::ActionRole);removeButton=buttons->addButton(LText(LocalText::RemoveShortcut),QDialogButtonBox::DestructiveRole);auto *apiSettings=buttons->addButton(LText(LocalText::OpenAiApiSettings),QDialogButtonBox::ActionRole);auto *saveClose=buttons->addButton(LText(LocalText::SaveAndClose),QDialogButtonBox::AcceptRole);auto *cancel=buttons->addButton(LText(LocalText::Cancel),QDialogButtonBox::RejectRole);layout->addWidget(buttons);
        QWidget::setTabOrder(search,commands);QWidget::setTabOrder(commands,allowObsHotkeyControl);QWidget::setTabOrder(allowObsHotkeyControl,editButton);QWidget::setTabOrder(editButton,removeButton);QWidget::setTabOrder(removeButton,apiSettings);QWidget::setTabOrder(apiSettings,saveClose);QWidget::setTabOrder(saveClose,cancel);LoadData();refresh();commands->editRequested=[this]{editSelected();};commands->removeRequested=[this]{removeSelected();};commands->closeRequested=[this]{close();};QObject::connect(search,&QLineEdit::textChanged,[this]{refresh(selectedIndex());});QObject::connect(commands,&QListWidget::currentItemChanged,[this](QListWidgetItem*,QListWidgetItem*){updateButtons();});QObject::connect(commands,&QListWidget::itemDoubleClicked,[this](QListWidgetItem*){editSelected();});QObject::connect(editButton,&QPushButton::clicked,[this]{editSelected();});QObject::connect(removeButton,&QPushButton::clicked,[this]{removeSelected();});QObject::connect(apiSettings,&QPushButton::clicked,[]{ShowSettings();});QObject::connect(saveClose,&QPushButton::clicked,[this]{if(saveAll()){closing=true;accept();}});QObject::connect(cancel,&QPushButton::clicked,[this]{close();});resize(900,700);search->setFocus(Qt::OtherFocusReason);
    }
    void focusSearch(){if(isMinimized())showNormal();else if(!isVisible())show();if(QApplication::activeWindow()!=this){raise();activateWindow();}if(QApplication::focusWidget()!=search)search->setFocus(Qt::OtherFocusReason);}
};

static void ShowQtHotkeyEditor(){
    if(qtHotkeyEditor){static_cast<QtHotkeyEditorDialog*>(qtHotkeyEditor.data())->focusSearch();return;}auto *editor=new QtHotkeyEditorDialog(obsMainWindow);qtHotkeyEditor=editor;editor->show();editor->raise();editor->activateWindow();
}

static bool InitializeAccessibleToolsAction(){
    if(!api.add_tools_qaction||!obsMainWindow)return false;auto *action=static_cast<QAction*>(api.add_tools_qaction("Accessible OBS Studio"));if(!action)return false;accessibleToolsAction=action;QObject::connect(action,&QAction::triggered,[]{ShowQtHotkeyEditor();});return true;
}
